import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider"
import { RolesLoadingProvider } from "@/app/providers/RolesLoadingProvider"
import { DevToolbar } from "@/app/components/DevToolbar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr" suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange={true}
        >
          <RolesLoadingProvider>
            <div className="container p-4 py-8 max-w-4xl mx-auto space-y-6 min-h-screen">
              {children}
            </div>
            <DevToolbar />
          </RolesLoadingProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
