name: Deploy Louap on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/infra/apps/louap
            git pull origin main
            cp .env.production .env
            
            # Construire et démarrer les conteneurs
            docker compose build
            docker compose up -d